spring.application.name=found
spring.profiles.include=jasypt
jasypt.encryptor.bootstrap=true


# 서버 포트
server.port=8080

# 마리아디비
spring.datasource.url=ENC(b93sbiytZy82ZZN8EmyyBy2LHcA5CsheSWpgkbJ8qr4AhO++bVxDXR+th2GQCLWK)
spring.datasource.username=ENC(dJHl+8pB/p/8DhTNtH08gg==)
spring.datasource.password=ENC(febkLRQPWeI7FvwFQ0Mglg==)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 마이바티스
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.human.found.domain.**
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# thymeleaf
spring.thymeleaf.cache=false


# # 1. 파일 임포트 구문을 최상단에 배치하고 명시적으로 파일 프로퍼티를 바인딩
# spring.config.import=file:./local.properties

# # 2. Jasypt 기본 설정
# jasypt.encryptor.algorithm=PBEWithMD5AndDES
# jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

# 서버 구동 시 DB 연결을 즉시 확인하고 실패하면 에러를 발생시킴
# spring.datasource.hikari.initialization-fail-timeout=1
